#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
rm -r constant/extendedFeatureEdgeMesh/
rm constant/triSurface/*.eMesh
touch $(basename $PWD).foam

#------------------------------------------------------------------------------
